# 生产环境配置文件

#  服务器启动的端口号
server:
  port: 8080

spring:
  application:
    name: onlinedoc-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    hikari:
      # 池中维护的最小空闲连接数，默认为 10 个
      minimum-idle: 10
      # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个
      maximum-pool-size: 10

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}
    database: ${REDIS_DATABASE}
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 32
        # 连接池中的最大空闲连接
        max-idle: 16
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        # max-wait: 5000ms

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: false
      fail_on_empty_beans: false
    defaultPropertyInclusion: NON_NULL
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true

  #  下面这个mvc和web配置，是为了使请求不存在的url时，能够按照通用返回模板返回（在全局异常处理器捕获NoHandlerFoundException即可）
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

#  mapper对应的xml文件存放路径，开启 mybatis 下划线命名法自动到驼峰命名法映射
mybatis-plus:
  mapper-locations: classpath*:edu/nwpu/onlinedoc/infrastructure/*/persistence/mysql/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以不在逻辑删除字段配置 @TableLogic)(若某表不使用逻辑删除，不在表中添加该字段即可)
      logic-delete-field: dataStatus
      # 逻辑已删除值(默认为 1)
      logic-delete-value: id
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0

# 启用生产环境专用日志格式
logging:
  pattern:
    console: "%X{traceId} %X{userId} %d{yyyy-MM-dd}T%d{HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%-1p} %-1logger{39} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

# 生成JWT相关配置
jwt:
  private-key-path: ${JWT_PRIVATE_KEY_PATH}
  private-key-output-path: ${JWT_PRIVATE_KEY_OUTPUT_PATH}
  public-key-path: ${JWT_PUBLIC_KEY_PATH}
  public-key-output-path: ${JWT_PUBLIC_KEY_OUTPUT_PATH}
  expiration-minutes: ${JWT_EXPIRATION_MINUTES}
  algorithm: RSA
