# 测试环境配置文件

#  服务器启动的端口号
server:
  port: 8080
  servlet:
    context-path: /buildBaseFrame
    jsp:
      init-parameters:
        mapped: false

spring:
  application:
    name: buildBaseFrame

  security:
    user:
      name: syj
      password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: online_exam
    password: 12345
    url: jdbc:mysql://localhost:3306/baseframe?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    hikari:
      # 池中维护的最小空闲连接数，默认为 10 个
      minimum-idle: 10
      # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个
      maximum-pool-size: 10

  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 32
        # 连接池中的最大空闲连接
        max-idle: 16
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        # max-wait: 5000ms
    timeout: 5000
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: false
      fail_on_empty_beans: false
    defaultPropertyInclusion: NON_NULL
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true

  #  下面这个mvc和web配置，是为了使请求不存在的url时，能够按照通用返回模板返回（在全局异常处理器捕获NoHandlerFoundException即可）
  mvc:
    view:
      prefix: / #/admin/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher
    #throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true

#  mapper对应的xml文件存放路径，开启 mybatis 下划线命名法自动到驼峰命名法映射
mybatis-plus:
  mapper-locations: classpath*:com/example/buildBaseFrame/infrastructure/*/persistence/mysql/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    # Redis缓存配置
    cache:
      enabled: true # 开启Redis缓存
      type: redis # Redis缓存类型
      ttl: 60000 # Redis缓存过期时间，单位为毫秒，默认值为-1，即永不过期
      flush-interval: 60000 # Redis缓存刷新时间，单位为毫秒，默认值为-1，即永不刷新
      size: 1000 # Redis缓存大小，默认值为0，即不限制缓存大小
  global-config:
    db-config:
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以不在逻辑删除字段配置 @TableLogic)(若某表不使用逻辑删除，不在表中添加该字段即可)
      logic-delete-field: dataStatus
      # 逻辑已删除值(默认为 1)
      logic-delete-value: id
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0

# 生成JWT相关配置
jwt:
  private-key-path: auto-gen-1024
  expiration-minutes: 1440
  algorithm: RSA

# 微信登录相关配置
### QQ
#constants:
#  qqAppId: 101513767
#  qqAppSecret: b1d978cefcf405388893d8e686d307b0
#  qqRedirectUrl: http://127.0.0.1:8080/QQLogin


#### 微信
#constants:
#  weCatAppId: wxa997b110821cbfd6
#  weCatAppSecret: a5cee82a40995afc5bc14d17058908c1
#  weCatRedirectUrl: http://192.168.1.2

# 微信开放平台 appid
wx:
  open:
    app_id: wx1292a69b2cd3c5b7
    # 微信开放平台 appsecret
    app_secret: dd776adcd6bb79a9a05a30e3a67ed7b3
    # 微信开放平台重定向url，即扫码登录后回调的后端api，中间的ip地址是内网穿透的
    redirect_url: http://2462bd30.r6.cpolar.top/buildBaseFrame/api/v1/user/wechat/login/wx


jasypt:
  encryptor:
    # 加密的盐值，为了安全，该配置可以放在启动参数或者命令行参数中
    password: fa7bd4edd42448aea8c9484fbce6e8cd
    # 加密所采用的算法
    algorithm: PBEWITHHMACSHA512ANDAES_256
